<?php
define('AUSTRALIA',1);
define('AUSTRIA',1);
define('BELGIUM',0);
define('CANADA',0);
define('DENMARK',1);
define('ESTONIA',1);
define('FINLAND',1);
define('FRANCE',1);
define('GERMANY',1);
define('HONGKONG',1);
define('HUNGARY',0);
define('IRELAND',1);
define('ISRAEL',1);
define('ITALY',1);
define('LITHUANIA',1);
define('MEXICO',0);
define('NETHERLANDS',1);
define('NORWAY',1);
define('POLAND',1);
define('PUERTORICO',0);
define('SPAIN',1);
define('SWEDEN',1);
define('SWITZERLAND',1);
define('UNITEDKINGDOM',1);
define('UNITEDSTATES',0);
?>